config/routes.rb
Rails.application.routes.draw do

	resources :posts
	get 'welcome/index'
	get 'welcome/about'
	get 'welcome/contact'
	
	root 'welcome#index'

	
end

app/models/post.rb
class Post < ActiveRecord::Base
	mount_uploader :postimg, PostimgUploader, dependent: :destroy
	validate  :picture_size

	# Validates the size of an uploaded picture.
    def picture_size
      if postimg.size > 5.megabytes
        errors.add(:postimg, "should be less than 5MB")
      end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]

	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.create post_params
		if @post.save
			redirect_to @post, notice: "Post succesfully created"
		else
			render 'new', notice: "Ooops, something went wrong!"
		end
	end

	def edit
	end

	def update
		if @post.update post_params
			redirect_to post_path, notice: "Post succesfully updated"
		else
			render 'new', notice: "Ooops, something went wrong!"
		end
	end

	def destroy
		@post.destroy
		redirect_to posts_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :content, :postimg, :remove_postimg)
	end

	def find_post
		@post = Post.find(params[:id])
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@index = true
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title='')
		base_title = 'Blog and Portfolio template'
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.haml
.border

%header
	.headline.center
		%i.fa.fa-diamond
		- if @index
			%h1 Woppie
		- else
			%h1
				=yield(:title)

		%h5 Blog & Portfolio Page

%nav
	.container
		%ul.left
			%li
				= link_to 'Home', root_path
			%li
				= link_to 'About', welcome_about_path
			%li
				= link_to 'Projects', "#"
			%li
				= link_to 'Blog', posts_path
			%li
				= link_to 'Contact', welcome_contact_path

		%ul.right
			%li
				= link_to "http://facebook.com" do
					%i.fa.fa-facebook
			%li
				= link_to "http://twitter.com" do
					%i.fa.fa-twitter
			%li
				= link_to "http://plus.google.com" do
					%i.fa.fa-google-plus
			%li
				= link_to "http://instagram.com" do
					%i.fa.fa-instagram
			%li
				= link_to "http://pinterest.com" do
					%i.fa.fa-pinterest
			%li
				= link_to "", id: "search" do
					%i.fa.fa-search
			%li
				= render "layouts/search_form"

app/views/layouts/_search_form.html.haml
#search_form
	%input{:type => "text"}/

app/views/layouts/application.html.haml
!!!
%html
	%head
		%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
		%title 
			= full_title(yield (:title))
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
		%link{:rel => "stylesheet", :href => "https://fonts.googleapis.com/icon?family=Material+Icons"}/
		= javascript_include_tag 'application', 'data-turbolinks-track' => true
		= csrf_meta_tags
	%body
		= render 'layouts/header'
		= yield

app/views/posts/_form.html.haml
= simple_form_for @post, html: { multipart: true } do |f|
	=f.input :title
	=f.label :content
	=f.text_field :content
	=f.file_field :postimg, accept: 'image/jpeg,image/gif,image/png'
	- if f.object.postimg?
		=image_tag(@post.postimg.thumb.url)
		=f.check_box :remove_postimg, id: "post_remove_postimg"
		=f.label :remove_postimg, "Remove Post Image"
	=f.button :submit

app/views/posts/edit.html.haml
%h2 Edit blog post

= render 'posts/form'

app/views/posts/index.html.haml
- provide :title, 'Blog'

.container
	=link_to "New Post", new_post_path, class: "btn"
	- @posts.each do |post|
		%h2
			= link_to post.title, post_path(post)

app/views/posts/new.html.haml
.container
	%h2 New blog post

	= render 'posts/form'

app/views/posts/show.html.haml
.container
	
	= image_tag @post.postimg.url if @post.postimg

	%h1
		= @post.title
	%p
		= @post.content

	= link_to "Back", posts_path, class: "btn"
	= link_to "Edit", edit_post_path(@post), class: "btn"
	= link_to "Delete", post_path(@post), method: :delete, data:{ confirlm: "Are you sure?" }, class: "btn"

app/views/welcome/about.html.haml
- provide :title, "About"
%h1 About Page

app/views/welcome/contact.html.haml
- provide :title, 'Contact'

%h1 Contact Page

app/views/welcome/index.html.haml
- provide :title, 'Home'

#main-content
	.container
		.row
			.post-content.col.s9
				.row
					.content-title 
						%h5 Latest Blog Posts
						= link_to 'view all posts', posts_path
					.col.s6
						.card
							.card-image
								=image_tag("blog1.jpg")
								.card-date
									%p 2015
									%hr/
									%p March 13
								.card-comment
									%i.fa.fa-comments
									%hr/
									%p 13
							.card-content
								%span.card-title Post title
								%p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt explicabo consequuntur quis distinctio, ducimus. Nostrum facere, debitis eum eligendi magnam cumque omnis! Sapiente ea tempore, repellat voluptas accusantium quia! Aut?
							.card-action
								%a{:href => "#", class: "waves-light btn"} Read more

					.col.s6
						.card
							.card-image
								=image_tag("blog2.jpg")
							.card-content
								%span.card-title Post title
								%p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt explicabo consequuntur quis distinctio, ducimus. Nostrum facere, debitis eum eligendi magnam cumque omnis! Sapiente ea tempore, repellat voluptas accusantium quia! Aut?
							.card-action
								%a{:href => "#", class: "waves-light btn"} Read more

				.row
					%h5.content-title Latest Projects
					.col.s4
						.card
							.card-image
								=image_tag("blog4.jpg")
							.card-content
								%span.card-title Project title
								%p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt explicabo consequuntur quis distinctio, ducimus. Nostrum facere, debitis eum eligendi magnam cumque omnis! Sapiente ea tempore, repellat voluptas accusantium quia! Aut?
							.card-action
								%a{:href => "#", class: "waves-light btn"} Read more
					.col.s4
						.card
							.card-image
								=image_tag("blog5.jpg")
							.card-content
								%span.card-title Project title
								%p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt explicabo consequuntur quis distinctio, ducimus. Nostrum facere, debitis eum eligendi magnam cumque omnis! Sapiente ea tempore, repellat voluptas accusantium quia! Aut?
							.card-action
								%a{:href => "#", class: "waves-light btn"} Read more
					.col.s4
						.card
							.card-image
								=image_tag("blog6.jpg")
							.card-content
								%span.card-title Project title
								%p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt explicabo consequuntur quis distinctio, ducimus. Nostrum facere, debitis eum eligendi magnam cumque omnis! Sapiente ea tempore, repellat voluptas accusantium quia! Aut?
							.card-action
								%a{:href => "#", class: "waves-light btn"} Read more

			.sidebar.col.s3
				.row
					.col.s12
						%p.about-me About me
						.card
							.card-image
								=image_tag("avatar.jpg")
							.card-content
								%p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt explicabo consequuntur quis distinctio, ducimus. Nostrum facere, debitis eum eligendi magnam cumque omnis!
				.row
					.col.s12
						.card-panel
							%h6 
								Popular Posts
							%ul.popular
								%li
									%a{:href => "#"} Popular Post #1
								%li
									%a{:href => "#"} Popular Post #1
								%li
									%a{:href => "#"} Popular Post #1
				.row
					.col.s12
						.card-panel
							%h6 
								Popular Categories
							%ul.popular
								%li
									%a{:href => "#"} Popular Category #1
								%li
									%a{:href => "#"} Popular Category #1
								%li
									%a{:href => "#"} Popular Category #1

%footer.page-footer
	.container
		.row
			.col.l6.s12
				%h5.white-text Footer Content
				%p.grey-text.text-lighten-4 You can use rows and columns here to organize your footer content.
			.col.l4.offset-l2.s12
				%h5.white-text Links
				%ul
					%li
						%a.grey-text.text-lighten-3{:href => "#!"} Link 1
					%li
						%a.grey-text.text-lighten-3{:href => "#!"} Link 2
					%li
						%a.grey-text.text-lighten-3{:href => "#!"} Link 3
					%li
						%a.grey-text.text-lighten-3{:href => "#!"} Link 4
	.footer-copyright
		.container
			© 2016 Copyright Text
			%a.grey-text.text-lighten-4.right{:href => "#!"} More Links